HAND_MAP = {"*": "L", "#": "S", "?": "U"}

BATTING_MAP = {
    "gp": "G",
    "gs": "GS",
    "ba": "batting_avg",
    "ob_pct": "onbase_perc",
    "slg_pct": "slugging_perc",
    "r": "R",
    "ab": "AB",
    "h": "H",
    "2b": "2B",
    "3b": "3B",
    "tb": "TB",
    "hr": "HR",
    "rbi": "RBI",
    "bb": "BB",
    "hbp": "HBP",
    "sf": "SF",
    "sh": "SH",
    "k": "SO",
    "sb": "SB",
    "cs": "CS",
    "ibb": "IBB",
    "opp_dp": "GIDP",
    "picked": "picked",
    "rbi2out": "rbi_with_2_outs",
}

PITCHING_MAP = {
    "app": "G",
    "gs": "GS",
    "era": "earned_run_avg",
    "ip": "IP",
    "cg": "CG",
    "h": "H",
    "r": "R",
    "er": "ER",
    "bb": "BB",
    "so": "SO",
    "sho": "SHO",
    "bf": "batters_faced",
    "bk": "BK",
    "hr_a": "HR",
    "wp": "WP",
    "hb": "HBP",
    "ibb": "IBB",
    "w": "W",
    "l": "L",
    "sv": "SV",
    "pickoffs": "pickoffs",
    "pitches": "pitches",
    "go": "go",
    "fo": "fo",
    "kl": "kl",
    "p_oab": "p_oab",
    "2b_a": "2B",
    "3b_a": "3B",
    "inh_run": "inherited_runners",
    "inh_run_score": "inherited_score",
    "sha": "SHA",
    "sfa": "SFA",
}

